#!/bin/bash

set -e

cd "$(dirname "$0")"/..

rm -rf build
mkdir build

cd api

echo "Building API - Linux"

GOOS=linux GOARCH=386 go build -o ../build/api-linux-386 -ldflags "-s -w"
GOOS=linux GOARCH=amd64 go build -o ../build/api-linux-amd64 -ldflags "-s -w"

echo "Building API - Windows"

GOOS=windows GOARCH=386 go build -o ../build/api-windows-386 -ldflags "-s -w"
GOOS=windows GOARCH=amd64 go build -o ../build/api-windows-amd64 -ldflags "-s -w"

echo "Building API - macOS"

GOOS=darwin GOARCH=amd64 go build -o ../build/api-darwin-amd64 -ldflags "-s -w"

cd ../worker

echo "Building worker - Linux"

GOOS=linux GOARCH=386 go build -o ../build/worker-linux-386 -ldflags "-s -w"
GOOS=linux GOARCH=amd64 go build -o ../build/worker-linux-amd64 -ldflags "-s -w"

echo "Building worker - Windows"

GOOS=windows GOARCH=386 go build -o ../build/worker-windows-386 -ldflags "-s -w"
GOOS=windows GOARCH=amd64 go build -o ../build/worker-windows-amd64 -ldflags "-s -w"

echo "Building worker - macOS"

GOOS=darwin GOARCH=amd64 go build -o ../build/worker-darwin-amd64 -ldflags "-s -w"
