#!/bin/bash

set -e

TAG=${1:-latest}

echo "Tagging images as $TAG..."

docker tag dsock-api dsock/api:$TAG
docker tag dsock-worker dsock/worker:$TAG

echo "Pushing images..."

docker push dsock/api:$TAG
docker push dsock/worker:$TAG
