debug = true
log_requests = true
redis_db = 0
redis_host = "redis:6379"
redis_password = ""
token = "abc123"
jwt_secret = "abc123"
default_channels = "global"
messaging_method = "direct"

# Worker only
direct_message_hostname = "worker"
direct_message_port = "80"
