name: CI

on: [push, pull_request]

jobs:
  build:
    name: E2E
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: sh scripts/run-e2e
